theme: jekyll-theme-minimal
title: Ekaterina Labkovich
logo: 
show_downloads: true
social-network-links:
  rss: true
  email: "labkovitch.katrin@gmail.com"
  linkedin: linkedin.com/in/ekaterina-labkovich
share-links-active:
  linkedin: true
